### ISSUE TITLE
So, abandonware?

### ISSUE THREAD

**Issue by padillla** [jakearchibald/sprite-cow#60]
I can see the last commit was many years ago and it doesn't currently work on chrome and hangs in firefox.

**Comment by jakearchibald** [comment]
Just tested in Chrome & it appears to work fine. Can you be a bit more specific in your bug report?

**Comment by padillla** [comment]
Really? 
My apologies, I saw the dates and assumed it was not longer mantained. 

The problem is, it resets and the CSS below doesn't change. Then it expands to take all the image and not the section I selecting.

See screencast:  http://recordit.co/hpGYfEUO4O

**Comment by jakearchibald** [comment]
That's not how it works. See the demo.

**Comment by padillla** [comment]
Oh, you are right. it does automatic detection of images,  but is not allowing to feely select an area.

I should be able to sprite out that section.

Thanks for your super fast response, I'll keep looking.

**Comment by jakearchibald** [comment]
For future reference: you're likely to get better responses if you include the actual bug in bug reports 😀
