### ISSUE TITLE
http://spritecow.com/ loads a different site.

### ISSUE THREAD

**Issue by kiranvj** [jakearchibald/sprite-cow#61]
http://spritecow.com/ loads a different site but http://www.spritecow.com/ loads the correct site. Is it intentional? 

![image](https://user-images.githubusercontent.com/3539487/32945546-e0b63f2e-cbb9-11e7-9944-16c786a1da85.png)

**Comment by jakearchibald** [comment]
Not intentional, but it was a limitation in serving from S3 when I built this. I don't know if that's still the case.
