### ISSUE TITLE
Opt-in for monero mining?

### ISSUE THREAD

**Issue by psyklon-project** [jakearchibald/sprite-cow#63]
Title says it all... At least don't use 100% CPU it can seriously damage older computers.

**Comment by jakearchibald** [comment]
wtf?? I have no idea how this got in there. Will remove it tomorrow. Thanks so much for pointing this out.

**Comment by psyklon-project** [comment]
You're welcome. First I noticed that my laptop gets very noisy when I open the site, so I looked into the source and found malicious looking code in the js file. Following the links I have fonnd a fake jquery cdn delivering the miner code, embedding it into a hidden iframe. By the way I have no problem with sites doing this - still better than flashing ads and popups - but at least ask me please, and do not kill my PC. :) Other than that it's a very useful little app, keep up the good work.

**Comment by jakearchibald** [comment]
The site is deployed to a s3 bucket that was run by an agency I worked at at the time. I'm guessing they've let someone less trustworthy have the details. Will switch the hosting to something I'm in control of tomorrow.

**Comment by jakearchibald** [comment]
Fixed. Might take 24hrs for the DNS to bounce around, but I'm getting the fixed site here.

**Comment by psyklon-project** [comment]
Yes it's okay now, loading the clean js from the  /9 directory. Thanks for your quick response!
