### ISSUE TITLE
Selects multiple sprites instead of one.

### ISSUE THREAD

**Issue by RewardedIvan** [jakearchibald/sprite-cow#66]
![image](https://user-images.githubusercontent.com/67065165/112726911-720f4800-8f28-11eb-869f-08d04e5c68b1.png)
I mean you can see the issue...
Basically, it selects multiple sprites instead of one.

**Comment by jakearchibald** [comment]
There needs to be a gap between the sprites of at least one pixel. This improves rendering too.
